### PR TITLE
#143 -- Add isInitialized check for PHP 7.4 typed properties.

### PR DESCRIPTION
**Pull request by BusterNeece**
See issue #143 for details.

Some help writing the unit tests for this would be much appreciated; not sure how to best approach testing a version-specific piece of functionality like this.

### CODE REVIEW

**Comment by SlvrEagle23** [comment]
It's also possible that it would be a better idea to have the `isInitialized` check happen _after_ the filters, but if there are any filters that use the existing property's value, they have the possibility of throwing TypeErrors in that situation.

**Comment by BusterNeece** [comment]
Minor update: the `$property->isInitialized($object)` method also requires that `setAccessible(true)` be set _before_ it is checked, in the same style as `getValue`, so it needs to be moved further down in the processing. The latest commit takes care of that.

**Comment by theofidry** [comment]
Thanks for the patch!

I think for the test you could create a fixture class with typed properties along the existing ones, a test cloning it once the properties are initialised and another when it's not. Since this test should be done only in PHP 7.4 you can use a `@requires PHP 7.4` tag to it

**Comment by BusterNeece** [comment]
I've created some PHP-7.4-specific unit tests and a new test class namespace to specifically address this functionality. I also added PHP 7.4 as a testing target for Travis CI.

Coveralls seems to think that the overall coverage is reduced...since this is a PHP 7.4-specific block of code, maybe that check should be suppressed for other versions?

**Review by mnapoli — APPROVED** [review]
Since the build issue is just coveralls being picky, to me it's OK to merge.

@theofidry good for you?

**Comment by theofidry** [comment]
Good for me 👍

**Comment by mnapoli** [comment]
Thank you @SlvrEagle23

**Pull request merged**
