### PR TITLE
Ignore `readonly` properties

### PR DESCRIPTION
**Pull request by llupa**
I am opening this PR as a starting point and to address #174

### CODE REVIEW

**Comment by mnapoli** [comment]
What will this code do? It seems like readonly properties would be empty. Shouldn't it contain the value of the original object? (else it's not really cloning)

**Comment by llupa** [comment]
Yes the same value is in both origin and clone objects. The assertion function in this package checks both arguments have equal values but they are not the same object.

I did try it with simple use cases, I can add more tests as a next step.

**Comment by mnapoli** [comment]
Oh ok awesome thanks! Let's run the CI!

**Comment by llupa** [comment]
I saw the CI failing for all version below 8.1, I think I misunderstood how `@requires` works. Will update this in the upcoming days!

Edit: @mnapoli I added test fixtures in their new dedicated namespace. I have 2 classes, 1 with 3 sample scalar readonly properties and another one with readonly object property typed from the former class. 

I did try this in a test branch and I know it passes. If you think that the assertion does not let this be very transparent, I can also just compare the property values one by one. As you wish

**Comment by mnapoli** [comment]
It's green 🙌

**Pull request merged**
