### PR TITLE
Add filter prepend method

### PR DESCRIPTION
**Pull request by fink3l**
Same request with #131 but for 1.x version.

### CODE REVIEW

**Comment by theofidry** [comment]
Thanks, I'll merge & tag it once I'm back from holidays next week. Ping me again if I forget about it too long

**Comment by fink3l** [comment]
@theofidry thanks)

**Comment by fink3l** [comment]
@theofidry ping?)

**Comment by theofidry** [comment]
Thanks! Sorry for the delay

**Pull request merged**
