### PR TITLE
Temporary fix to run tests on Travis

### PR DESCRIPTION
**Pull request by Slamdunk**
1. https://twitter.com/slamzoe/status/1002090034382635008
1. https://twitter.com/seldaek/status/1002097015831121920

### CODE REVIEW

**Comment by Slamdunk** [comment]
For Scrutinizer something similar should be adopted:
https://scrutinizer-ci.com/docs/guides/setting_environment_variables

It could also be set with a commit configuration file, if you prefer.

**Comment by theofidry** [comment]
>It could also be set with a commit configuration file, if you prefer.

I think this would be better: I don't have control on the Scrutinizer account at the moment

Thanks a lot for the help!

**Comment by Slamdunk** [comment]
Done. Scrutinizer triggers seem stalled, but the build passed the stage this PR aims to.

**Comment by theofidry** [comment]
Hm maybe it needs the complete config. Prior to your changes it was:

```
filter:
    excluded_paths: [vendor/*, app/*, web/*]
    
before_commands:
    - "composer install"

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    php_loc: true
    php_mess_detector: true
    php_analyzer: true
    php_code_coverage: true
```

**Comment by Slamdunk** [comment]
I've messed up and can't figure out why the variable is not taken into account anymore :smiley:

**Comment by theofidry** [comment]
maybe we can just export it manually in the `before_commands`?

**Comment by Slamdunk** [comment]
Mmm :confused:

**Comment by Slamdunk** [comment]
Ok, the first version of the configuration was good, PR ready to merge

**Comment by theofidry** [comment]
Thanks very much!

**Pull request merged**
