### PR TITLE
Remove invalid php `use`

### PR DESCRIPTION
**Pull request by hiscaler**

### CODE REVIEW

**Comment by theofidry** [comment]
Hi, thanks for the PR! Unfortunately this use statement is perfectly valid. It means you are using an outdated version of PHP with which [this library is not compatible](https://github.com/myclabs/DeepCopy/blob/1.x/composer.json#L24)

**Comment by hiscaler** [comment]
I am sorry! But why use this looks invalid code to compatible PHP version.

**Comment by theofidry** [comment]
It's perfectly valid as of PHP 5.6+: https://www.php.net/manual/en/language.namespaces.importing.php. Our CI would not pass at all otherwise :)

**Comment by hiscaler** [comment]
@theofidry Oh, Thank you.

**Pull request closed without merging**
